title: "Andrés Solares"

home:
  greeting: ANDRÉS SOLARES
  subgreeting: Robotics engineer
  description: I'm always involved in exciting projects, continuously seeking opportunities to learn and express my creativity.

about:
  greeting: I'm Andrés.
  image: "/images/hallstat_cisne_recorte.jpg"
  description: |
    I'm a data scientist with a background in physics who loves unraveling insights from complex data.<br><br>
    When I'm not crunching numbers, you'll find me immersed in software and game development, creating music, exploring art, and diving into the fascinating realms of AI.<br><br>
    My passion lies in machine learning, natural language processing, and computer vision, where I get to blend science and creativity to push the boundaries of what's possible.<br><br>
    Down below you'll find more information about me. If you'd like to get in touch, feel free to send me a message!

projects:
  greeting: "My Projects."
  description: "Here are some of the projects I've been working on recently."

navigation:
  - title: "Home"
    href: "/"

  - title: "About"
    href: "/about"
  
  - title: "Projects"
    href: "/projects"

  - title: "Contact"
    href: "/contact"
  
projects-list:
  - name: "Blob Out!"
    href: "https://divingavran.itch.io/blob-out"
    image: "/images/blob-out.png"
    created: "2022-06-18"
    updated: "2022-06-18"
  
  - name: "Flappy Raven"
    href: "https://divingavran.itch.io/flappy-raven"
    image: "/images/flappy-raven.png"
    created: "2023-02-22"
    updated: "2023-02-22"
  
  - name: "The Royal Game of Ur"
    href: "https://divingavran.itch.io/the-royal-game-of-ur"
    image: "/images/the-royal-game-of-ur.png"
    created: "2022-07-17"
    updated: "2022-07-17"

# Social Media
# url: link to the account
# icon: FontAwesome 5 icon name (https://fontawesome.com/v5/search?o=r&m=free)
social-media:

  - name: "GitHub"
    url: "https://github.com/divin"
    icon: "fab fa-github"

  - name: "YouTube"
    url: "https://www.youtube.com/@divingavran"
    icon: "fab fa-youtube"

  - name: "Itch.io"
    url: "https://divingavran.itch.io"
    icon: "fab fa-itch-io"
  
  - name: "Patreon"
    url: "https://patreon.com/divingavran"
    icon: "fab fa-patreon"

  - name: "Bandcamp"
    url: "https://divin.bandcamp.com"
    icon: "fab fa-bandcamp"

  - name: "SoundCloud"
    url: "https://soundcloud.com/divingavran"
    icon: "fab fa-soundcloud"

education:
  - name: "Polytechnic University of Madrid: Master in Automation and Robotics"
    icon: "fas fa-graduation-cap"
    from: "September 2020"
    to: "September 2021"
    description: >-
      - Master's Thesis: Locomotion by means of transformable wheels for an intervention robot. Development from scratch, mechanical and electronic design and construction of a functional prototype using additive manufacturing techniques (3D printing). In patent process
      
      - Master's Thesis grade: 9.8
      
      - Average grade: 9.11
  
  - name: "University of Oviedo: Degree in Industrial Electronics and Automation Engineering."
    icon: "fas fa-graduation-cap"
    from: "September 2016"
    to: "July 2020"
    description: >-
      - Activities and groups: 
        - Runner-up of Spain badminton by universities (Cartagena 2017) 
        - Collaborator of the association DRONE4STUDENTS (2016-2017)
      - Degree's Thesis: Navigation system for an indoor mobile robot. Development of a navigation system in integration with a commercial robotic platform using ROS and simulation in Gazebo. Development of a safe people tracking system
            
      - Degree's Thesis grade: 10
      
      - Average grade: 6.5

  - name: "FH Joanneum: Erasmus+ Program"
    icon: "fas fa-graduation-cap"
    from: "September 2019"
    to: "February 2020"
    description: >-
      6-month stay at the FH Joanneum University (Graz, Austria) under the Erasmus+ program of the degree, studying for the Master's degree in electronics and computer engineering

# Skills in percent
skills:
  languages:
    - name: Spanish (Native)
      value: 100
    
    - name: English (C1)
      value: 80

  coding:
    - name: Python
      value: 100
    
    - name: HTML
      value: 80
    
    - name: CSS
      value: 60

    - name: SQL
      value: 60
    
    - name: GScript
      value: 80
    
  python:
    - name: NumPy
      value: 90
    
    - name: Pandas
      value: 90
    
    - name: Matplotlib
      value: 90
    
    - name: Seaborn
      value: 70
    
    - name: Scikit-Learn
      value: 80
    
    - name: PyTorch
      value: 60

  tools:
    - name: Git
      value: 75

    - name: Linux
      value: 75
    
    - name: Docker
      value: 40

    - name: Jupyter
      value: 100
    
    - name: VSCode
      value: 100
    
    - name: Blender
      value: 25
    
    - name: Logic Pro
      value: 80
    
    - name: Final Cut
      value: 50
    
    - name: Godot
      value: 80

contact:
  message: "Feel free to contact me via phone or email."
  name: Andrés Solares Jurado
  email: andresolaresjurado@gmail.com
  phone: +34 634 768 285
  city: Gijón
  province: Asturias
  country: Spain


website:
  font_size: "0.5rem"
  font_family: "Ubuntu"
  font_weight: "200"
  max_width: "1280px"
  
  colors:
    text: "#dbeadf"
    background: "#323E42"
    primary: "#8A6FDF"
    secondary: "#8A6FDF"
    accent: "#8A6FDF"